Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark 1.svg, Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark 2.svg, Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark.svg, Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/Contents.json, Projects/Core/DesignSystem/Sources/CheckBox/DotoriCheckBox.swift, Projects/Core/DesignSystem/Sources/Icons/DotoriIcon.swift
DesignSystem DotoriCheckBox 추가
=> 🔀 :: DesignSystem DotoriCheckBox 추가

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift, Tuist/Dependencies.swift, Tuist/ProjectDescriptionHelpers/Target/Target+MicroFeature.swift
Demo 모듈에서 Hot Reload를 하기 위해 Inject를 사용해 적용했습니다.
- Inject 모듈 추가
- Demo 모듈 Build Settings에 Inject용 세팅 추가
- Demo모듈에 Inject 의존성 추가
=> 🔀 :: Inject를 사용한 Hot Reload를 적용

Projects/Core/JwtStore/Sources/JwtStoreAssembly.swift, Projects/Core/JwtStore/Sources/KeychainJwtStore.swift, Projects/Core/KeyValueStore/Sources/KeyValueStoreAssembly.swift, Projects/Domain/AuthDomain/Sources/Assembly/AuthDomainAssembly.swift, Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift, Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
- struct로 된 공유 객체들을 class로 변경합니다.
- 또한 DI를 할 때 공유가 많이 되는 객체들의 경우 단일 객체 하나로 여러번 우려먹기 할 수 있게 DI를 합니다
- struct to class
- Swinject Container scope for Singleton DI
=> 🔀 :: struct로 된 공유 객체들의 타입을 class로 변경 및 싱글톤 DI

Projects/Feature/NoticeFeature/Sources/Scene/NoticeStore.swift, Projects/Feature/NoticeFeature/Sources/Scene/NoticeViewController.swift, Projects/Feature/NoticeFeature/Tests/NoticeFeatureTest.swift
- 공지 리스트 tableView에 refresh 기능을 추가
- viewWillAppear action -> fetchNoticeList action 이름 변경
=> 🔀 :: 공지 Feature Refresh 기능 추가

Projects/Feature/BaseFeature/Sources/Base/BaseModalViewController.swift, Projects/Feature/BaseFeature/Sources/Base/BaseStoredModalViewController.swift, Projects/Feature/BaseFeature/Sources/Base/BaseStoredViewController.swift, Projects/Feature/BaseFeature/Sources/Base/BaseViewController.swift, Projects/Feature/ConfirmationDialogFeature/Sources/Scene/ConfirmationDialogViewController.swift, Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift, Projects/Feature/NoticeFeature/Sources/Scene/NoticeViewController.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift, Projects/Feature/SplashFeature/Sources/Scene/SplashViewController.swift
기존의 BaseViewController에서 한 번 더 추상화해서 BaseStoredViewController를 만듭니다
- BaseViewController를 BaseStoredViewController로 추상화하여 Store가 없는 버전의 혹은 Store가 여러개인 버전의 viewController 작성을 할 수 있도록 작업
- 기존 BaseViewController를 상속하는 ViewController들을 BaseStoredViewController를 상속하도록 변경
- 기존 BaseModalViewController를 상속하는 ViewController들을 BaseStoredModalViewController를 상속하도록 변경
=> 🔀 :: BaseViewController와 BaseStoredViewController 분리

Projects/Feature/SelfStudyFeature/Sources/Scene/SelfStudyViewController.swift
PR이 머지될때 어디쪽에 우선순위가 쏠린건지 SelfStudyViewController가 BaseStoredViewController를 상속받는거로 변경되지 않은상태로 머지되었습니다.
SelfStudyViewController가 BaseStoredViewController를 상속받도록 변경합니다.
SelfStudyViewController가 BaseStoredViewController를 상속받도록 변경
SelfStudyViewController가 BaseStoredViewController를 상속받도록 변경
=> 🔀 :: SelfStudyViewController가 BaseStoredViewController를 상속받도록 변경

Projects/App/Support/Info.plist
TestFlight에 올릴 때 수출 규정 관련해서 뭐 이러쿵저러쿵 해야하는데 저희는 연관된게 없으니 NO로 설정해서 패스해줍니다
=> 🔀 :: 수출 규정 관련 Info.plist 설정

Projects/Feature/SelfStudyFeature/Sources/Scene/SelfStudyViewController.swift, Projects/UserInterface/Localization/Resources/en.lproj/SelfStudy.strings, Projects/UserInterface/Localization/Resources/ko.lproj/SelfStudy.strings
SelfStudyFeature에 지역화가 적용되지 않은 부분이 있어서 지역화를 적용했습니다.
=> 🔀 :: 지역화가 적용되지 않은 SelfStudyFeature에 지역화 적용

Projects/Feature/SelfStudyFeature/Sources/Scene/View/SelfStudyCell.swift
다크모드일때 자습 Cell의 성별 아이콘이 어두워서 잘 안보였습니다.
성별 아이콘 Cell의 tintColor를 n10으로 두어 해결하였습니다.
성별 아이콘의 rendering모드를 original로 두고, tintColor를 n10으로 설정
=> 🔀 :: 자습 Cell에서 다크모드일때 성별 아이콘 색이 잘 안보이는 현상 해결

Projects/Feature/MainTabFeature/Sources/Moordinator/MainTabMoordinator.swift
TabBar Image를 조정해주었습니다.
위로 조금 올라가 있던 TabBarImage들을 가운데로 조정해주었습니다
=> TabBar Image 위치 조정

Projects/Feature/FilterSelfStudyFeature/Sources/Scene/FilterSelfStudyViewController.swift, Projects/Shared/CombineUtility/Sources/UIGestureRecognizer/UIGestureRecognizer+publisher.swift
ModalViewController에서 빈화면을 누를때만이 아니라 실제 content가 들어가있는 contentView를 누를때 똑같이 dismiss route를 보내는 현상이 있었음
tapGesturePublisher에서 해당 gesture의 view인지 검사
gesture의 touch인식 view를 해당 gesture를 추가한 view인지 검사
=> 🔀 :: [#142] ModalViewController의 dismiss가 subviews를 눌러도 적용되는 현상

Projects/Feature/FilterSelfStudyFeature/Sources/Scene/FilterSelfStudyViewController.swift
FilterSelfStudyViewController에서 BaseDomainInterface를 의존하지도 않은 상태로 import해서 죽입니다.
=> 🔀 :: [#174] 의존성이 없음에도 import를 하는 코드 제거

Projects/App/ShareExtension/Sources/DotoriShareViewController.swift, Projects/App/ShareExtension/Support/Info.plist
유튜브 share inputItem이 plain-text인데 현재는 url만 받아요, 그래서 plain-text도 됩니다 이제!
- 공유 대상에 plain-text 지원
- ShareExtension 코드 메서드 분리 위주 리팩토링
- 공유 대상에 plain-text 지원
=> 🔀 :: [#181] ShareExtension 버그 해결

Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
자습신청에 성공했을 때 토스트 메시지가 안마의자 신청에 성공했다고 뜨는 것을 수정
=> 🔀 :: [#180] 자습신청 성공 문구 정상화

Projects/Feature/NoticeFeature/Sources/Scene/NoticeViewController.swift, Projects/UserInterface/DesignSystem/Sources/Extension/UINavigationItem+dotoriBackButton.swift
공지 상세 페이지의 뒤로가기 버튼을 디자인과 일치시키기
- 도토리 스타일의 뒤로가기 버튼 extension화
- 공지 상세 페이지의 뒤로가기 버튼이 기본 뒤로가기 버튼이였던 것을 실제 디자인과 맞게 만들어줍니다
<div>
</div>
```swift
self.navigationitem.configDotoriBackButton()
self.navigationitem.configDotoriBackButton(title: "Asdf")
```
=> 🔀 :: [#185] 공지 상세 페이지 뒤로가기 버튼 디자인 반영

Projects/Feature/MassageFeature/Sources/Scene/MassageStore.swift, Projects/Feature/MassageFeature/Sources/Scene/MassageViewController.swift, Projects/Feature/SelfStudyFeature/Sources/Scene/SelfStudyViewController.swift, Projects/Shared/CombineUtility/Sources/Publisher/Publisher+not.swift
기존에 자습, 안마의자 ViewController에서 자습, 안마 신청리스트를 가져올 때 viewDidLoad에서 가져옴
-> 이로인한 문제로, 첫번째로 데이터를 가져오는 시점에 데이터가 빈 상태로오고 이후에는 백엔드상에 데이터가 있어도 다시 가져오지 않는 문제 발생
- 자습, 안마의자 화면에서 Refresh 허용
- 자습, 안마의자 화면에서 데이터 가져오는 시점 변경 viewDidLoad -> viewWillAppear
=> 🔀 :: [#201] 데이터 fetching 시점 변경

Projects/Core/Networking/Interface/Interceptor/Jwt/JwtAuthorizable.swift
토큰 재발급 API 변경으로 인해 토큰 재발급에 실패해서 AccessToken 만료시 바로 로그아웃되었어요.
변경된 API에 맞게 refreshToken을 Refresh-Token으로 변경했어요.
=> 🔀 :: [#225] 토큰 재발급 API 수정

Projects/Domain/MusicDomain/Sources/DTO/Response/FetchMusicListResponseDTO.swift
기상음악 신청 리스트에서 신청 시간이 현재 시간으로 화면에 나오는 현상이 있었어요.
createdTime 포맷을 수정하였어요.
=> 🔀 :: [#227] createdTime format 수정

Projects/Domain/MassageDomain/Interface/Entity/MassageRankEntity.swift, Projects/Domain/MassageDomain/Sources/DTO/Response/FetchMassageRankListResponseDTO.swift, Projects/Domain/MassageDomain/Tests/FetchMassageRankListUseCaseTests.swift, Projects/Domain/MassageDomain/Tests/MassageRepositoryTests.swift, Projects/Domain/SelfStudyDomain/Interface/Entity/SelfStudyRankEntity.swift, Projects/Domain/SelfStudyDomain/Sources/DTO/Response/FecthSelfStudyRankListResponseDTO.swift, Projects/Domain/SelfStudyDomain/Tests/FetchSelfStudyRankListUseCaseTests.swift, Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift, Projects/Feature/HomeFeature/Sources/Assembly/HomeAssembly.swift, Projects/Feature/HomeFeature/Sources/Factory/HomeFactoryImpl.swift, Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift, Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore+State.swift, Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift, Projects/Feature/HomeFeature/Tests/HomeFeatureTest.swift, Projects/Feature/MassageFeature/Demo/Sources/AppDelegate.swift, Projects/Feature/MassageFeature/Sources/Scene/View/MassageCell.swift, Projects/Feature/MassageFeature/Tests/MassageFeatureTest.swift, Projects/Feature/SelfStudyFeature/Demo/Sources/AppDelegate.swift, Projects/Feature/SelfStudyFeature/Sources/Scene/SelfStudyStore.swift, Projects/Feature/SelfStudyFeature/Sources/Scene/View/SelfStudyCell.swift, Projects/UserInterface/DesignSystem/Sources/CardView/AppliedStudentCardView.swift
자습신청, 안마의자 신청 페이지에서 프로필 이미지가 보일 수 있게 수정했습니다.
자습신청, 안마의자 신청 페이지에서 프로필 이미지가 보일 수 있게 수정
=> 🔀 :: [#237] 자습신청자 페이지, 안마의자 신청자 페이지에서 프로필 이미지 보여주기

.github/workflows/AppStore.yml
개발할때부터 xcode 15로 하는만큼 GitHub Action workflow의 runner들도 macos 14 이상으로는 돌여야할거같아요.
AppStore workflow의 runner환경을 macos-14로 변경했어요.
=> 🔀 :: [#233] runner 환경 macos14 업그레이드
