Projects/Core/DWebKit/Demo/Sources/AppDelegate.swift, Projects/Feature/RenewalPasswordFeature/Sources/RenewalPasswordFactoryImpl.swift, Projects/Feature/SignupFeature/Sources/Factory/SignupFactoryImpl.swift
https://www.dotori-gsm.com 로 웹뷰를 로드하도록 변경하였습니다
웹뷰 URL 변경
웹뷰 URL
https://dotori-v2.vercel.app
-> 
https://www.dotori-gsm.com
=> 🔀 :: Dotori 웹뷰 URL 변경

.github/workflows/CI.yml
=> 💚 :: Discord Mention after failed to CI

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift, Projects/Feature/BaseFeature/Project.swift, Projects/Feature/BaseFeature/Sources/Base/BaseStore.swift, Projects/Feature/BaseFeature/Sources/Base/BaseViewController.swift, Projects/Feature/BaseFeature/Sources/Protocol/HasCancellableBag.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninStore.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift, Projects/Shared/CombineUtility/Sources/Publisher/Publisher+sink.swift, Tuist/Dependencies.swift
https://github.com/GSM-MSG/Store
를 기반으로 하여 상태관리 아키텍쳐를 변경 및 마이그레이션하였습니다.
- Store 디펜던시 추가
- 상태관리 아키텍쳐 마이그레이션
- Store 변경
- https://github.com/GSM-MSG/Store
=> 🔀 :: 상태관리 아키텍처 마이그레이션

.github/CODEOWNERS
- CODEOWNERS를 설정합니다
- baekteun, kimsh153, minaje0917, MelBIP, junseopark0331, uuuunseo
위의 6명을 CODEOWNERS로 등록합니다
아 이거 Team-Ampersand Organization으로 레포 import하고 할까여
=> 🔀 :: CODEOWNERS 설정

Scripts/CodeSigning.swift, Scripts/GenerateModule.swift, Scripts/InitEnvironment.swift, Scripts/NewDependency.swift
Script 실행 중 취소 가능하게 변경합니다
- Script 안에 취소 signal 감지를 추가하여 취소 키 입력이 들어오면 스크립트를 멈춥니다.
=> 🔀 :: Script 실행 중 취소 가능하게 변경

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift, Projects/App/Sources/Application/AppDelegate.swift, Projects/Feature/BaseFeature/Project.swift, Tuist/Dependencies.swift
IQKeyboardManager를 적용합니다.
- IQKeyboardManagerSwift 의존성 추가
- IQKeyboardManager 활성화
=> 🔀 :: IQKeyboardManager 적용

Projects/Domain/BaseDomain/Sources/Interceptor/Jwt/JwtInterceptor.swift, Tuist/Dependencies.swift
Emdpoint 버전 최신버전으로 갱신화
Emdpoint 버전 3.2.4 -> 3.2.6
=> 🔀 :: Emdpoint 버전 업그레이드

Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift, Plugin/L10nPlugin/Plugin.swift, Plugin/L10nPlugin/ProjectDescriptionHelpers/L10n.swift, Plugin/L10nPlugin/ResourceSynthesizers/Strings.stencil, Projects/Domain/AuthDomain/Interface/Error/AuthDomainError.swift, Projects/Domain/AuthDomain/Sources/Error/AuthDomainError+description.swift, Projects/Domain/BaseDomain/Project.swift, Projects/Feature/BaseFeature/Project.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift, Projects/UserInterface/Localization/Project.swift, Projects/UserInterface/Localization/Resources/en.lproj/Global.strings, Projects/UserInterface/Localization/Resources/en.lproj/Home.strings, Projects/UserInterface/Localization/Resources/en.lproj/Main.strings, Projects/UserInterface/Localization/Resources/en.lproj/Massage.strings, Projects/UserInterface/Localization/Resources/en.lproj/Music.strings, Projects/UserInterface/Localization/Resources/en.lproj/Notice.strings, Projects/UserInterface/Localization/Resources/en.lproj/SelfStudy.strings, Projects/UserInterface/Localization/Resources/en.lproj/Signin.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Global.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Home.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Main.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Massage.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Music.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Notice.strings, Projects/UserInterface/Localization/Resources/ko.lproj/SelfStudy.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Signin.strings, Projects/UserInterface/Localization/Sources/Source.swift, Tuist/Config.swift, Tuist/ProjectDescriptionHelpers/Project+Template.swift
지역화를 위한 모듈 생성 및 사용성 설정
- Localization 모듈 생성
- L10n 전용 Plugin 생성
- L10n용 stencil 작성
- Signin 관련 도메인에 L10n 적용
```swift
label.text = L10n.Signin.signinButtonTitle
```
=> 🔀 :: 지역화 설정

Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift, Projects/App/Project.swift, Projects/App/Sources/Application/AppDelegate.swift, Projects/Core/Database/Project.swift, Projects/Core/JwtStore/Project.swift, Projects/Core/KeyValueStore/Interface/HasKeyValueStore.swift, Projects/Core/KeyValueStore/Interface/KeyValueStore.swift, Projects/Core/KeyValueStore/Interface/StorableKeys.swift, Projects/Core/KeyValueStore/Project.swift, Projects/Core/KeyValueStore/Sources/KeyValueStoreAssembly.swift, Projects/Core/KeyValueStore/Sources/UserDefaultsKeyValueStore.swift, Projects/Core/KeyValueStore/Testing/DictionaryKeyValueStore.swift, Projects/Domain/AuthDomain/Project.swift, Projects/Domain/AuthDomain/Sources/Assembly/AuthDomainAssembly.swift, Projects/Domain/BaseDomain/Project.swift, Projects/Domain/BaseDomain/Sources/Base/BaseRemoteDataSource.swift, Projects/Domain/BaseDomain/Sources/Endpoint/DotoriRestAPIDomain.swift, Projects/Domain/BaseDomain/Sources/Interceptor/Logging/DotoriLogginInterceptor.swift, Projects/Domain/BaseDomain/Sources/Interceptor/Role/DotoriRoleDTO.swift, Projects/Domain/BaseDomain/Sources/Interceptor/Role/DotoriRoleInterceptor.swift, Projects/Domain/UserDomain/Interface/Interface.swift, Projects/Domain/UserDomain/Interface/UserRoleType.swift, Projects/Domain/UserDomain/Project.swift, Projects/Domain/UserDomain/Sources/Source.swift, Projects/Domain/UserDomain/Testing/Testing.swift, Projects/Domain/UserDomain/Tests/UserDomainTest.swift
통신 후 Local에 유저 권한을 저장하는 로직 추가
- DotoriRoleInterceptor 작업
- KeyValueStore의 Key 저장 방식 변경
=> 🔀 :: Local에 유저 권한 저장 로직 자동화

Tuist/Dependencies.swift
MSGLayout의 버전을 1.2.0으로 업그레이드합니다
- MSGLayout 1.1.0 -> 1.2.0
=> 🔀 :: MSGLayout 버전 업그레이드

Projects/Feature/BaseFeature/Sources/Base/BaseModalViewController.swift
Modal 페이지에서 사용할 BaseModalViewController를 작업했습니다
- BaseModalViewController
=> 🔀 :: BaseModalViewController

Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
=> 🔀 :: iOS 최소 배포 버전 15.0

Projects/Domain/MassageDomain/Interface/DataSource/RemoteMassageDataSource.swift, Projects/Domain/MassageDomain/Interface/Repository/MassageRepository.swift, Projects/Domain/MassageDomain/Interface/UseCase/CancelMassageUseCase.swift, Projects/Domain/MassageDomain/Sources/Assembly/MassageDomainAssembly.swift, Projects/Domain/MassageDomain/Sources/DataSource/Remote/MassageEndpoint.swift, Projects/Domain/MassageDomain/Sources/DataSource/Remote/RemoteMassageDataSourceImpl.swift, Projects/Domain/MassageDomain/Sources/Repository/MassageRepositoryImpl.swift, Projects/Domain/MassageDomain/Sources/UseCase/CancelMassageUseCaseImpl.swift, Projects/Domain/MassageDomain/Testing/DataSource/RemoteMassageDataSourceSpy.swift, Projects/Domain/MassageDomain/Testing/Repository/MassageRepositorySpy.swift, Projects/Domain/MassageDomain/Testing/UseCase/CancelMassageUseCaseSpy.swift, Projects/Domain/SelfStudyDomain/Interface/DataSource/RemoteSelfStudyDataSource.swift, Projects/Domain/SelfStudyDomain/Interface/Repository/SelfStudyRepository.swift, Projects/Domain/SelfStudyDomain/Interface/UseCase/CancelSelfStudyUseCase.swift, Projects/Domain/SelfStudyDomain/Sources/Assembly/SelfStudyDomainAssembly.swift, Projects/Domain/SelfStudyDomain/Sources/DataSource/Remote/RemoteSelfStudyDataSourceImpl.swift, Projects/Domain/SelfStudyDomain/Sources/DataSource/Remote/SelfStudyEndpoint.swift, Projects/Domain/SelfStudyDomain/Sources/Repository/SelfStudyRepositoryImpl.swift, Projects/Domain/SelfStudyDomain/Sources/UseCase/CancelSelfStudyUseCaseImpl.swift, Projects/Domain/SelfStudyDomain/Testing/DataSource/RemoteSelfStudyDataSourceSpy.swift, Projects/Domain/SelfStudyDomain/Testing/Repository/SelfStudyRepositorySpy.swift, Projects/Domain/SelfStudyDomain/Testing/UseCase/CancelSelfStudyUseCaseSpy.swift, Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift, Projects/Feature/HomeFeature/Sources/Assembly/HomeAssembly.swift, Projects/Feature/HomeFeature/Sources/Factory/HomeFactoryImpl.swift, Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift, Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift, Projects/Feature/HomeFeature/Tests/HomeFeatureTest.swift, Projects/UserInterface/Localization/Resources/en.lproj/Home.strings, Projects/UserInterface/Localization/Resources/ko.lproj/Home.strings
하하 누가 실수로 자습, 안마를 취소하는 기능을 안만들었네요 ^^7
- CancelSelfStudyUseCase
- CancelMassageUseCase
=> 🔀 :: HomeFeature에 자습, 안마 취소 기능 추가

Projects/Shared/UIKitUtil/Sources/Adapter/CollectionView/CollectionViewAdapter.swift
CollectionView를 위한 Adapter를 작업했습니다.
- CollectionViewAdapter
=> 🔀 :: CollectionViewAdapter 작업

Projects/Feature/HomeFeature/Sources/Moordinator/HomeMoordinator.swift, Projects/Feature/MusicFeature/Sources/Moordinator/MusicMoordinator.swift
iPad일때는 ActionSheet를 preset못하기에 Alert로 바꿔서 present시킵니다
=> 🔀 :: [#140] iPad에서 ActionSheet를 Alert로 present

.github/workflows/AppStore.yml
CD를 하면 Info.plist의 버전을 변경시키는데 이를 master에 반영합니다
=> 🔀 :: [#157] CD 이후 버전 변경사항 master에 반영

.github/workflows/AppStore.yml
=> 💚 :: AppStoreCD / run 환경 macos로 변경

.gitconfig, .githooks/pre-commit, Makefile, Scripts/Setup.sh
GitHooks를 구성합니다
- pre-commit
- 커밋하기 전, SwiftFormat을 실행합니다
현재는 format으로 파일 바뀌면 다시 커밋하라고 시비거는데,
swiftformat으로 인해 파일이 변경되어도 구대로 commit 실행할까요?
=> 🔀 :: [#86] GitHooks 구성

Tuist/ProjectDescriptionHelpers/Action+Template.swift, Tuist/ProjectDescriptionHelpers/Enum/GenerateEnvironment.swift
=> 🔀 :: [#200] Build Phase에서 SwiftFormat 제거

Projects/Feature/HomeFeature/Sources/Scene/View/MealContentStackView.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift
급식이 없을때 View에서 급식이 없습니다를 나타내는 기능 구현
급식이 없을때 View에서 급식이 없습니다를 나타내는 기능 구현했습니다.
DotoriLabel 타입을 배열로 하는 mealsView를 생성하여 meals배열이 비어있을때 
"급식이 없습니다"를 View의 윗부분으로 올리기 위해 공백과 함께 배열에 추가했습니다.
mealViews.append(DotoriLabel("급식이 없습니다."))
mealViews.append(DotoriLabel(""))
mealViews.append(DotoriLabel(""))
mealViews.append(DotoriLabel(""))
mealViews.append(DotoriLabel(""))
mealViews.append(DotoriLabel(""))
mealViews.append(DotoriLabel(""))
이 코드 너무 안예뻐보이는데 다른 방법이 있으면 알려주세요..!
=> 🔀:: [#184] 급식이 없을때 "급식이 없습니다"를 나타나게끔 수정

Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift, Projects/Domain/AuthDomain/Project.swift, Projects/Feature/SigninFeature/Project.swift, Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift, Tuist/Dependencies.swift
GAuth 로그인에서 기존 로그인으로 복구
GAuth 로그인에서 기존 로그인으로 복구했습니다.
=> 🔀 :: [#219] GAuth 로그인에서 기존 로그인으로 복구

Plugin/TemplatesPlugin/Templates/Module/Project.stencil, Scripts/GenerateModule.swift
모듈 생성 자동화 스크립트 수정
모듈 생성 자동화 스크립트를 수정했어요
=> 🔀 :: [#218] 모듈 생성 자동화 스크립트 수정

Projects/App/ShareExtension/Support/Info.plist, Projects/App/Support/Info.plist, Projects/Feature/HomeFeature/Sources/Scene/View/MealContentStackView.swift
세로 모드로 고정되게끔 수정
세로 모드로 고정되게끔 수정했어요
=> 🔀 :: [#223] 세로모드로 고정되게 수정

Projects/App/Support/Info.plist
아이패드 가로모드 지원
아이패드로 가로모드가 지원되도록 수정했어요.
=> 🔀 :: [#231] 아이패드 가로모드 지원

Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift, Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore+State.swift, Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift, Projects/Shared/CombineUtility/Sources/Publisher/Publisher+async.swift, Projects/Shared/CombineUtility/Sources/Publisher/Publisher+catchToNever.swift
본인의 프로필 이미지를 메인 페이지에 띄울 수 있게끔 수정했습니다.
fetchProfileImage를 통해 메인페이지에 프로필 이미지를 띄우게끔 수정했어요
=> 🔀 :: [#237] 본인의 프로필 이미지를 메인 페이지에 보여주기
